version: '3'

services:
  db:
    container_name: cmosdb
    image: postgres:12
    environment:
      POSTGRES_PASSWORD : danielpaul
  web:
    container_name: cmosapp
    build: .
    command: python manage.py runserver
    volumes:
      - .:/canteen
    ports:
      - "8000:8000"
    depends_on:
      - db